OpenFIPS201_CHANGE_REFERENCE_DATA_ADMIN_Schema DEFINITIONS IMPLICIT TAGS ::= 
BEGIN

ChangeReferenceDataKeyRequest ::= SEQUENCE {
	element CHOICE	{
		key		[0] OCTET STRING (SIZE(16..32)),
		rsaN	[1] OCTET STRING (SIZE(128..256)),
		rsaE	[2] OCTET STRING (SIZE(3)),
		rsaP	[3] OCTET STRING (SIZE(128..256)),
		rsaQ	[4] OCTET STRING (SIZE(64..128)),
		rsaDP	[5] OCTET STRING (SIZE(64..128)),
		rsaDQ	[6] OCTET STRING (SIZE(64..128)),
		rsaPQ	[7] OCTET STRING (SIZE(64..128)),
		eccW	[8] OCTET STRING (SIZE(32..48)),
		eccS	[9] OCTET STRING (SIZE(32..48)),
		smCVC	[10] OCTET STRING (SIZE(1..256))
	}
}

END